runtime: python311

env_variables:
  ENVIRONMENT: "production"
  REDIS_HOST: "/cloudsql/your-project:your-region:your-instance"

entrypoint: gunicorn -b :$PORT secure-data-system-device:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
